remove invalid import class: com.cloudera.recordservice.thrift.TProtocolVersion in core
- As the type change of ProtocolVersion from enum to string, we also need to remove the invalid import class,
otherwise it will get compilation error.

Change-Id: Ic6cd9f5959cc07a99696c1cce2e450b75467c3d6
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/8866
Reviewed-by: Chao Sun <chao.sun@cloudera.com>
Tested-by: jenkins
Reviewed-by: Li Li <lili@cloudera.com>
Tested-by: Li Li <lili@cloudera.com>